### Numpy Tasks

#### 1. Write a NumPy program to multiply two given arrays of same size element-by-element.

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

arr3 = np.multiply(arr1,arr2)

arr3

array([ 7, 16, 27, 40, 55, 72])

#### 2. Write a NumPy program to find the missing data in a given array.

In [69]:
arr1 = np.array([32,98,76,86,np.nan,np.nan])

np.where(np.isnan(arr1))

(array([4, 5], dtype=int64),)

#### 3. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [3]:
arr1 = np.array([7,2,5,2,5,6])
arr2 = np.array([7,2,5,1,5,6])

np.array_equal(arr1,arr2)

False

#### 4. Write a NumPy program to save a NumPy array to a text file.

In [4]:
with open("file1.txt","w") as file1:
    arr1 = np.array(["1","2","3","4","5"])
    for i in arr1:
        file1.write(i)
        file1.write(" ")

#### 5. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

In [5]:
rand_arr = np.random.uniform(2.5,6.5,[30,])
rand_arr

array([2.91646235, 6.46504104, 6.39552682, 3.89875465, 4.18781485,
       3.92746188, 6.24335237, 3.66387686, 5.15046112, 4.83150332,
       4.39808002, 3.68393034, 3.28747365, 3.36528021, 2.9772248 ,
       4.6319232 , 3.78747304, 5.1391133 , 6.36519868, 5.19931899,
       3.43707416, 4.43025303, 6.11419561, 2.68918548, 3.642215  ,
       6.05528113, 3.59828334, 4.62198548, 5.43011241, 3.56710822])

### Pandas Tasks

In [6]:
import pandas as ps

#### 1. Write a Pandas program to convert Series of lists to one Series.

In [14]:
df = ps.Series([34,56,32,45,245],[43,54,65,45,23])
df

43     34
54     56
65     32
45     45
23    245
dtype: int64

#### 2. Write a Pandas program to create a subset of a given series based on value and condition.

In [17]:
df1 = ps.Series([23,45,65,32,43,44,34,43])

df1[df1%2==0]

3    32
5    44
6    34
dtype: int64

#### 3. Write a Pandas program to display most frequent value in a given series and replace everything else as Other in the series.

In [26]:
df1 = ps.Series([78,98,56,76,32,78,98,78])
a=df1.mode()[0]
df1[df1!=a]='other'
df1

C:\Users\ragha\AppData\Local\Temp\ipykernel_20904\3991824762.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'other' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1[df1!=a]='other'


0       78
1    other
2    other
3    other
4    other
5       78
6    other
7       78
dtype: object

#### 4 Write a Pandas program to find the positions of numbers that are multiples of 5 of agiven series.

In [34]:
df1 = ps.Series([5,10,64,60,34,54])

df1[df1%5==0].index

Index([0, 1, 3], dtype='int64')

#### 5. Write a Pandas program to calculate the number of characters in each word in a given series.

In [37]:
df2 = ps.Series(['Hi','Hello','How',"World",'Python'])

for i in df2:
    print(i,len(i))

Hi 2
Hello 5
How 3
World 5
Python 6


#### 6. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

In [62]:
from dateutil.parser import parse
date_series = ps.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


#### 7. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [41]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,260,270,220],
    'Out of':[300,300,300,300,300]
}

ds = ps.DataFrame(dict1,index=['Student1','Student2','Student3','Student4','Student5'])
ds

Students  Age  Marks  Out of
Student1      Jim   19    230     300
Student2   Dwight   19    235     300
Student3      Pam   19    260     300
Student4     John   20    270     300
Student5     Tony   19    220     300

#### 8. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [45]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,260,270,220],
    'Out of':[300,300,300,300,300],
    'No of Attempts':[1,2,1,3,3]
}
ds1 = ps.DataFrame(dict1)

ds1[ds1['No of Attempts']>2]

Students  Age  Marks  Out of  No of Attempts
3     John   20    270     300               3
4     Tony   19    220     300               3

#### 9. Write a Pandas program to append a new row k to data frame with given values for each column. Now delete the new row and return the original DataFrame.

In [65]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,120,270,100],
    'Out of':[300,300,300,300,300]
}
df4 = ps.DataFrame(dict1)

df4['k'] = [54,43,54,64,32]

print(df4)

df4.drop(['k'],axis=1)
df4

  Students  Age  Marks  Out of   k
0      Jim   19    230     300  54
1   Dwight   19    235     300  43
2      Pam   19    120     300  54
3     John   20    270     300  64
4     Tony   19    100     300  32


Students  Age  Marks  Out of   k
0      Jim   19    230     300  54
1   Dwight   19    235     300  43
2      Pam   19    120     300  54
3     John   20    270     300  64
4     Tony   19    100     300  32

#### 10. Write a Pandas program to sort the DataFrame first by name in descending order,then by score in ascending order.

In [55]:
dict1 = {
    'Names':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Score':[230,235,120,270,100],
    'Out of':[300,300,300,300,300],
}

df3 = ps.DataFrame(dict1)

df3 = df3.sort_values(['Names','Score'],ascending=[False,True])

df3

Names  Age  Score  Out of
4    Tony   19    100     300
2     Pam   19    120     300
3    John   20    270     300
0     Jim   19    230     300
1  Dwight   19    235     300

#### 11. Write a Pandas program to replace the &#39;qualify&#39; column contains the values &#39;yes&#39; and no with True and False.

In [52]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,120,270,100],
    'Out of':[300,300,300,300,300],
    'Qualify':['Yes','Yes','No','Yes','No']
}

ds2 = ps.DataFrame(dict1)

ds2['Qualify']= ds2['Qualify'].replace({'Yes':True,'No': False})
ds2

Students  Age  Marks  Out of  Qualify
0      Jim   19    230     300     True
1   Dwight   19    235     300     True
2      Pam   19    120     300    False
3     John   20    270     300     True
4     Tony   19    100     300    False

#### 12. Write a Pandas program to remove infinite values from a given DataFrame.

In [54]:
dict2 = {
    'X':[21,32,45,67,np.inf],
    'Y':[32,54,np.inf,98,89]
}

ds3 = ps.DataFrame(dict2)

ds3 = ds3.replace({np.inf:np.NaN})

ds3 = ds3.dropna()
ds3

X     Y
0  21.0  32.0
1  32.0  54.0
3  67.0  98.0