### Numpy Tasks

#### 1. Write a NumPy program to multiply two given arrays of same size element-by-element.

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

arr3 = np.multiply(arr1,arr2)

arr3

array([ 7, 16, 27, 40, 55, 72])

#### 2. Write a NumPy program to find the missing data in a given array.

In [22]:
arr1 = np.array([32,98,76,86,np.nan,np.nan])

np.where(np.isnan(arr1))

(array([4, 5], dtype=int64),)

#### 3. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [4]:
arr1 = np.array([7,2,5,2,5,6])
arr2 = np.array([7,2,5,1,5,6])

np.array_equal(arr1,arr2)

False

#### 4. Write a NumPy program to save a NumPy array to a text file.

In [5]:
with open("file1.txt","w") as file1:
    arr1 = np.array(["1","2","3","4","5"])
    for i in arr1:
        file1.write(i)
        file1.write(" ")

#### 5. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

In [6]:
rand_arr = np.random.uniform(2.5,6.5,[30,])
rand_arr

array([3.60320113, 4.10041321, 6.16593204, 3.31788614, 3.08491826,
       4.4015583 , 3.47183531, 2.84332273, 6.33559649, 3.99973636,
       4.5772856 , 4.03503015, 5.41920776, 4.82527188, 3.95084933,
       5.22752009, 5.6717676 , 5.07276732, 5.49118514, 2.56841091,
       5.49929913, 6.3080981 , 5.99708645, 4.49565803, 3.95500052,
       5.23065597, 6.42941435, 3.0660828 , 5.14686786, 4.61442711])

### Pandas Tasks

In [4]:
import pandas as ps

#### 1. Write a Pandas program to convert Series of lists to one Series.

In [8]:
df = ps.Series([34,56,32,45,245],[43,54,65,45,23])
df

43     34
54     56
65     32
45     45
23    245
dtype: int64

#### 2. Write a Pandas program to create a subset of a given series based on value and condition.

In [9]:
df1 = ps.Series([23,45,65,32,43,44,34,43])

df1[df1%2==0]

3    32
5    44
6    34
dtype: int64

#### 3. Write a Pandas program to display most frequent value in a given series and replace everything else as Other in the series.

In [5]:
data = ps.Series([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])

frequent = data.mode()[0]

data[data != frequent] = 'Other'
print(data)

0     Other
1     Other
2     Other
3     Other
4     Other
5     Other
6     Other
7     Other
8     Other
9     Other
10        5
11        5
12        5
13        5
14        5
dtype: object


#### 4 Write a Pandas program to find the positions of numbers that are multiples of 5 of agiven series.

In [11]:
df1 = ps.Series([5,10,64,60,34,54])

df1[df1%5==0].index

Index([0, 1, 3], dtype='int64')

#### 5. Write a Pandas program to calculate the number of characters in each word in a given series.

In [12]:
df2 = ps.Series(['Hi','Hello','How',"World",'Python'])

for i in df2:
    print(i,len(i))

Hi 2
Hello 5
How 3
World 5
Python 6


#### 6. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

In [13]:
from dateutil.parser import parse
date_series = ps.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


#### 7. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [14]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,260,270,220],
    'Out of':[300,300,300,300,300]
}

ds = ps.DataFrame(dict1,index=['Student1','Student2','Student3','Student4','Student5'])
ds

Students  Age  Marks  Out of
Student1      Jim   19    230     300
Student2   Dwight   19    235     300
Student3      Pam   19    260     300
Student4     John   20    270     300
Student5     Tony   19    220     300

#### 8. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [15]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,260,270,220],
    'Out of':[300,300,300,300,300],
    'No of Attempts':[1,2,1,3,3]
}
ds1 = ps.DataFrame(dict1)

ds1[ds1['No of Attempts']>2]

Students  Age  Marks  Out of  No of Attempts
3     John   20    270     300               3
4     Tony   19    220     300               3

#### 9. Write a Pandas program to append a new row k to data frame with given values for each column. Now delete the new row and return the original DataFrame.

In [16]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,120,270,100],
    'Out of':[300,300,300,300,300]
}
df4 = ps.DataFrame(dict1)

df4['k'] = [54,43,54,64,32]

print(df4)

df4.drop(['k'],axis=1)
df4

  Students  Age  Marks  Out of   k
0      Jim   19    230     300  54
1   Dwight   19    235     300  43
2      Pam   19    120     300  54
3     John   20    270     300  64
4     Tony   19    100     300  32


Students  Age  Marks  Out of   k
0      Jim   19    230     300  54
1   Dwight   19    235     300  43
2      Pam   19    120     300  54
3     John   20    270     300  64
4     Tony   19    100     300  32

#### 10. Write a Pandas program to sort the DataFrame first by name in descending order,then by score in ascending order.

In [17]:
dict1 = {
    'Names':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Score':[230,235,120,270,100],
    'Out of':[300,300,300,300,300],
}

df3 = ps.DataFrame(dict1)

df3 = df3.sort_values(['Names','Score'],ascending=[False,True])

df3

Names  Age  Score  Out of
4    Tony   19    100     300
2     Pam   19    120     300
3    John   20    270     300
0     Jim   19    230     300
1  Dwight   19    235     300

#### 11. Write a Pandas program to replace the &#39;qualify&#39; column contains the values &#39;yes&#39; and no with True and False.

In [18]:
dict1 = {
    'Students':['Jim',"Dwight","Pam","John","Tony"],
    'Age':[19,19,19,20,19],
    'Marks':[230,235,120,270,100],
    'Out of':[300,300,300,300,300],
    'Qualify':['Yes','Yes','No','Yes','No']
}

ds2 = ps.DataFrame(dict1)

ds2['Qualify']= ds2['Qualify'].replace({'Yes':True,'No': False})
ds2

Students  Age  Marks  Out of  Qualify
0      Jim   19    230     300     True
1   Dwight   19    235     300     True
2      Pam   19    120     300    False
3     John   20    270     300     True
4     Tony   19    100     300    False

#### 12. Write a Pandas program to remove infinite values from a given DataFrame.

In [19]:
dict2 = {
    'X':[21,32,45,67,np.inf],
    'Y':[32,54,np.inf,98,89]
}

ds3 = ps.DataFrame(dict2)

ds3 = ds3.replace({np.inf:np.NaN})

ds3 = ds3.dropna()
ds3

X     Y
0  21.0  32.0
1  32.0  54.0
3  67.0  98.0